---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  ansible_connection: ssh
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_host_key_checking: false
  ansible_verbosity: 2
  ansible_verbose: true
  requirements_path: requirements.yml

platforms:
  - name: debian/stretch64

suites:
  - name: default
