---
- name: RMQ | Create fluentbit directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - /var/log/td-agent-bit
    - /var/lib/td-agent-bit
    - /etc/td-agent-bit

- name: RMQ | Fluentbit rmq parser
  copy:
    src: etc/td-agent-bit/rmq_parser.conf
    dest: /etc/td-agent-bit/rmq_parser.conf
    mode: 0644
    owner: root
    group: root

- name: RMQ | configure fluentbit
  include_role:
    name: sitewards.fluentbit
  vars:
    sitewards__fluentbit__config_service_params:
      "Flush": 5
      "Daemon": "Off"
      "Log_Level": "info"
      "Log_File": "/var/log/td-agent-bit/td-agent-bit.log"
      "HTTP_Server": "Off"
      "Parsers_File": "rmq_parser.conf"
    sitewards__fluentbit__inputs:
      - "Name": tail
        "Multiline": on
        "Parser_Firstline": "rabbitmq"
        "Path": "/var/log/rabbitmq/rabbit*"
        "Path_Key": "path"
        "DB": "/var/lib/td-agent-bit/rabbitmq.flb.db"
        "Exclude_Path": "*.gz,*.xz"
        "Buffer_Max_Size": "1M"
        "Tag": "@clustername@-@environment@"
    sitewards__fluentbit__outputs:
      - "Name": forward
        "Match": "*"
        "Host": "@fluentd_host@"
        "Port": "24224"